### ISSUE TITLE
No stats returned for users for spaces in the names

### ISSUE THREAD

**Issue by pushontom** [Nekress/rainbowsix7nightbot#2]
Propose using profileId instead which users can get from their https://game-rainbow6.ubi.com/ URL

**Comment by Nekress** [comment]
Fixed. If you use whitespace characters for whatever reason you can now parse your profileId where you would put your nick as parameter. 
Your profileId has to match this RegEx:

`/[a-z0-9]{8}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{4}-[a-z0-9]{12}/ `

ExampleId: 77c4b04d-f7ed-4914-b911-44f1ef1a9b85
so make sure you copy & paste it correctly.
